### ISSUE TITLE
Unexpected token ILLEGAL in react-starter-kit ?

### ISSUE THREAD

**Issue by shashank734** [andreypopp/react-fa#35]
It's giving following error while using in react-starter-kit..

```
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/shashank/Documents/app/myapp/node_modules/react-fa/lib/index.js:13:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/shashank/Documents/app/myapp/build/webpack:/external "react-fa":1:1)
    at __webpack_require__ (/Users/shashank/Documents/app/myapp/build/webpack:/webpack/bootstrap ce37a2f4a67ae43bd49f:19:1)
```

**Comment by andreypopp** [comment]
I need more context, what webpack configuration do you use and etc. this
looks like misconfuguration to me.

**Comment by shashank734** [comment]
I am using following configuration ... I have modified the things you have suggested for font files..

https://github.com/kriasoft/react-starter-kit/blob/master/tools/webpack.config.js

```
   {
        test: /\.(png|jpg|jpeg|gif|svg|woff|woff2)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: 'url-loader',
        query: {
          name: DEBUG ? '[path][name].[ext]?[hash]' : '[hash].[ext]',
          limit: 10000,
        },
      },
      {
        test: /\.(eot|ttf|wav|mp3)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: 'file-loader',
        query: {
          name: DEBUG ? '[path][name].[ext]?[hash]' : '[hash].[ext]',
        },
      },
```

It's giving error in require(...) you are using in index.js

**Comment by andreypopp** [comment]
Are you using server side rendering? It looks like it tries to eval code in Node.js.

**Comment by shashank734** [comment]
yes it's isomorphic app any suggestions.. I have tried to comment this require() and included css my own than no errors but than it's showing nothing...

**Comment by andreypopp** [comment]
I'm not sure tbh, this is highly dependent on a specific boilerplate you are using. I suggest opening an issue there instead.
